# c:\Users\bill.liu\Desktop\Project\SideProject\reservation_system\client-nextjs\wrangler.toml

name = "reservation"
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "20"
# 新增這行來解決相依性衝突
NPM_FLAGS = "--legacy-peer-deps"
